#!/usr/bin/env bash
#check domains
domain=$1
subdomain=${2:-"www lb-01 web-01 web-02"}

for sub in $subdomain; do
    dest=$(dig +short "$sub"."$domain")
    type=$(dig "$sub"."$domain" | awk '/^'"${sub}"."${domain}"'/ { print $4 }' | cut -c1)
    echo "The subdomain $sub is a $type record and points to $dest"
done

