#!/usr/bin/env bash
#install nginx server
apt-get -y update
apt-get -y install nginx
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me return 301 https:\/\/google.com permanent;/" /etc/nginx/sites-available/default
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
