#!/usr/bin/env bash
#install HAproxy
sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAproxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 163926-web-01 100.26.243.4:80 check
    server 163926-web-02 52.86.172.136:80 check
EOF

service haproxy restart
