#!/usr/bin/env bash
#bash stuff
sed -i 's/listen\s*.\+;/listen 80;/g' /etc/nginx/sites-available/default
service nginx restartsed -i 's/listen\s*.\+;/listen 80;/g' /etc/nginx/sites-available/default
service nginx restart
